# Generated by Django 5.2.6 on 2025-09-10 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.URLField(choices=[('FW', 'Footwear'), ('Sh', 'Shirts'), ('misc', 'Misc')], default='FW', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
