# Generated by Django 5.2.6 on 2025-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("FW", "Footwear"), ("Sh", "Shirts"), ("misc", "Misc")],
                default="FW",
                max_length=20,
            ),
        ),
    ]
