# Generated by Django 5.2.6 on 2025-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FW', 'Footwear'), ('Sh', 'Shirts'), ('misc', 'Misc')], default='FW', max_length=20),
        ),
    ]
